{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "step-ca.fullname" . }}
  labels:
    {{- include "step-ca.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "step-ca.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      interval: {{ .Values.serviceMonitor.interval }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
