apiVersion: v1
kind: Service
metadata:
  name: {{ include "step-ca.fullname" . }}
  labels:
    {{- include "step-ca.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "step-ca.selectorLabels" . | nindent 4 }}
